# Generated by Django 5.2.8

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_additional_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(
                    blank=True,
                    help_text='Organization that owns this warehouse',
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='warehouses',
                    to='accounts.organization'
                )),
                ('created_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='+',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'db_table': 'warehouses',
                'ordering': ['name'],
                'indexes': [
                    models.Index(fields=['organization', 'is_active'], name='warehouses_org_active_idx'),
                    models.Index(fields=['name'], name='warehouses_name_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='+',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'db_table': 'products',
                'indexes': [
                    models.Index(fields=['sku'], name='products_sku_idx'),
                    models.Index(fields=['category', 'is_active'], name='products_cat_active_idx'),
                    models.Index(fields=['created_by'], name='products_creator_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=10)),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='stocks',
                    to='inventory.product'
                )),
                ('warehouse', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='stocks',
                    to='inventory.warehouse'
                )),
                ('created_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='+',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'db_table': 'stocks',
                'unique_together': [('product', 'warehouse')],
                'indexes': [
                    models.Index(fields=['warehouse', 'product'], name='stocks_wh_prod_idx'),
                    models.Index(fields=['quantity'], name='stocks_qty_idx'),
                ],
            },
        ),
    ]
