# Generated by Django 5.2.8 on 2025-11-20 10:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('predicted_quantity', models.IntegerField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='inventory.product')),
            ],
            options={
                'db_table': 'predictions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalesMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('metric_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sales_metrics',
                'ordering': ['-date'],
                'unique_together': {('date', 'metric_type')},
            },
        ),
    ]
